import { Button } from '@/Components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/Components/ui/card';
import { Input } from '@/Components/ui/input';
import { Label } from '@/Components/ui/label';
import { Head, Link, useForm } from '@inertiajs/react';
import { Eye, EyeOff, Wrench } from 'lucide-react';
import { FormEventHandler, useState } from 'react';

export default function Login({ status, canResetPassword }: { status?: string; canResetPassword: boolean }) {
    const { data, setData, post, processing, errors, reset } = useForm({ login: '', password: '', remember: false });
    const [showPassword, setShowPassword] = useState(false);
    const submit: FormEventHandler = (event) => { event.preventDefault(); post(route('login'), { onFinish: () => reset('password') }); };

    return <div className="min-h-screen bg-muted/30 px-4 py-8 sm:px-6 lg:grid lg:grid-cols-2 lg:p-0"><Head title="Masuk" />
        <section className="hidden bg-slate-950 p-12 text-slate-100 lg:flex lg:flex-col lg:justify-between xl:p-16"><Link href="/" className="flex w-fit items-center gap-3"><span className="flex size-9 items-center justify-center rounded-lg bg-primary"><Wrench className="size-4" /></span><span className="text-lg font-bold">FixIn</span></Link><div className="max-w-lg"><p className="mb-4 text-sm font-medium text-violet-300">Akses operasional</p><h1 className="text-4xl font-bold tracking-tight">Ruang kendali maintenance gedung.</h1><p className="mt-5 leading-7 text-slate-400">Kelola laporan, penugasan teknisi, dan bukti pekerjaan dalam satu tempat.</p></div><p className="text-sm text-slate-500">Masuk menggunakan username atau nomor WhatsApp terdaftar.</p></section>
        <main className="flex items-center justify-center lg:bg-background lg:p-12"><Card className="w-full max-w-md shadow-sm"><CardHeader><CardTitle>Masuk</CardTitle><CardDescription>Gunakan username atau nomor WhatsApp Anda.</CardDescription></CardHeader><CardContent>{status && <p className="mb-4 rounded-md bg-emerald-50 p-3 text-sm font-medium text-emerald-700">{status}</p>}<form onSubmit={submit} className="space-y-5"><div className="space-y-2"><Label htmlFor="login">Username atau Nomor WhatsApp</Label><Input id="login" type="text" autoComplete="username" placeholder="Masukkan username atau nomor WhatsApp" value={data.login} onChange={(event) => setData('login', event.target.value)} aria-invalid={!!errors.login} required autoFocus />{errors.login && <p className="text-sm font-medium text-destructive">{errors.login}</p>}</div><div className="space-y-2"><div className="flex items-center justify-between"><Label htmlFor="password">Password</Label>{canResetPassword && <Link href={route('password.request')} className="text-sm font-medium text-primary hover:underline">Lupa password?</Link>}</div><div className="relative"><Input id="password" type={showPassword ? 'text' : 'password'} autoComplete="current-password" value={data.password} onChange={(event) => setData('password', event.target.value)} className="pr-10" aria-invalid={!!errors.password} required /><Button type="button" variant="ghost" size="icon" className="absolute right-0 top-0" onClick={() => setShowPassword(!showPassword)} aria-label={showPassword ? 'Sembunyikan password' : 'Tampilkan password'}>{showPassword ? <EyeOff /> : <Eye />}</Button></div>{errors.password && <p className="text-sm font-medium text-destructive">{errors.password}</p>}</div><label className="flex items-center gap-2 text-sm text-muted-foreground"><input type="checkbox" className="size-4 rounded border-input accent-primary" checked={data.remember} onChange={(event) => setData('remember', event.target.checked)} />Ingat saya</label><Button type="submit" className="w-full" disabled={processing}>{processing ? 'Memproses...' : 'Masuk ke Dashboard'}</Button></form><p className="mt-6 text-center text-sm text-muted-foreground">Belum punya akun? <Link href={route('register')} className="font-medium text-primary hover:underline">Daftar</Link></p></CardContent></Card></main>
    </div>;
}
