import { Button } from '@/Components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/Components/ui/card';
import { Input } from '@/Components/ui/input';
import { Label } from '@/Components/ui/label';
import { Head, Link, useForm } from '@inertiajs/react';
import { Wrench } from 'lucide-react';
import { FormEventHandler } from 'react';

export default function Register() {
    const { data, setData, post, processing, errors, reset } = useForm({ name: '', username: '', phone_number: '', password: '', password_confirmation: '' });
    const submit: FormEventHandler = (event) => { event.preventDefault(); post(route('register'), { onFinish: () => reset('password', 'password_confirmation') }); };
    const error = (message?: string) => message && <p className="text-sm font-medium text-destructive">{message}</p>;

    return <div className="min-h-screen bg-muted/30 px-4 py-8 sm:px-6 lg:grid lg:grid-cols-2 lg:p-0"><Head title="Daftar" />
        <section className="hidden bg-slate-950 p-12 text-slate-100 lg:flex lg:flex-col lg:justify-between xl:p-16"><Link href="/" className="flex w-fit items-center gap-3"><span className="flex size-9 items-center justify-center rounded-lg bg-primary"><Wrench className="size-4" /></span><span className="text-lg font-bold">FixIn</span></Link><div className="max-w-lg"><p className="mb-4 text-sm font-medium text-violet-300">Akun penghuni</p><h1 className="text-4xl font-bold tracking-tight">Laporkan kerusakan dengan lebih mudah.</h1><p className="mt-5 leading-7 text-slate-400">Daftar untuk membuat laporan, melihat progres, dan menerima pembaruan perbaikan.</p></div><p className="text-sm text-slate-500">Akun terhubung dengan organisasi pada alamat situs ini.</p></section>
        <main className="flex items-center justify-center lg:bg-background lg:p-12"><Card className="w-full max-w-md shadow-sm"><CardHeader><CardTitle>Buat akun</CardTitle><CardDescription>Isi data berikut untuk mulai menggunakan FixIn.</CardDescription></CardHeader><CardContent><form onSubmit={submit} className="space-y-5"><div className="space-y-2"><Label htmlFor="name">Nama lengkap</Label><Input id="name" autoComplete="name" value={data.name} onChange={(event) => setData('name', event.target.value)} aria-invalid={!!errors.name} required autoFocus />{error(errors.name)}</div><div className="space-y-2"><Label htmlFor="username">Username</Label><Input id="username" autoComplete="username" placeholder="Gunakan huruf, angka, - atau _" value={data.username} onChange={(event) => setData('username', event.target.value)} aria-invalid={!!errors.username} required />{error(errors.username)}<p className="text-xs text-muted-foreground">Tidak boleh hanya berisi angka.</p></div><div className="space-y-2"><Label htmlFor="phone_number">Nomor WhatsApp</Label><Input id="phone_number" type="tel" autoComplete="tel" placeholder="Contoh: 081234567890" value={data.phone_number} onChange={(event) => setData('phone_number', event.target.value)} aria-invalid={!!errors.phone_number} required />{error(errors.phone_number)}</div><div className="space-y-2"><Label htmlFor="password">Password</Label><Input id="password" type="password" autoComplete="new-password" value={data.password} onChange={(event) => setData('password', event.target.value)} aria-invalid={!!errors.password} required />{error(errors.password)}</div><div className="space-y-2"><Label htmlFor="password_confirmation">Konfirmasi password</Label><Input id="password_confirmation" type="password" autoComplete="new-password" value={data.password_confirmation} onChange={(event) => setData('password_confirmation', event.target.value)} aria-invalid={!!errors.password_confirmation} required />{error(errors.password_confirmation)}</div><Button type="submit" className="w-full" disabled={processing}>{processing ? 'Membuat akun...' : 'Buat akun'}</Button></form><p className="mt-6 text-center text-sm text-muted-foreground">Sudah punya akun? <Link href={route('login')} className="font-medium text-primary hover:underline">Masuk</Link></p></CardContent></Card></main>
    </div>;
}
